import { Party, Item, Invoice, Expense, BankAccount, TaxConfiguration, FiscalYear, UserAccount, Company, PartyGroup, UnitMaster } from './types';

export const INITIAL_UNITS: UnitMaster[] = [
  { id: 'unit-1', code: 'PCS', name: 'Pieces', uqcCode: 'PCS-PIECES', description: 'Standard unit for individual count items', defaultConversion: 'Base Unit' },
  { id: 'unit-2', code: 'BOX', name: 'Boxes', uqcCode: 'BOX-BOXES', description: 'Master shipping box', defaultConversion: '1 Box = 10 Packs' },
  { id: 'unit-3', code: 'PACK', name: 'Packets', uqcCode: 'PAC-PACKETS', description: 'Intermediate pack quantity', defaultConversion: '1 Pack = 10 Pcs' },
  { id: 'unit-4', code: 'KG', name: 'Kilograms', uqcCode: 'KGS-KILOGRAMS', description: 'Weight measurement unit', defaultConversion: '1 KG = 1000 Grams' },
  { id: 'unit-5', code: 'GM', name: 'Grams', uqcCode: 'GMS-GRAMMES', description: 'Precision weight unit', defaultConversion: '1000 Grams = 1 KG' },
  { id: 'unit-6', code: 'ROLL', name: 'Rolls', uqcCode: 'ROL-ROLLS', description: 'Length coils / cable rolls', defaultConversion: 'Base Unit' },
  { id: 'unit-7', code: 'MTR', name: 'Meters', uqcCode: 'MTR-METERS', description: 'Linear distance measurement', defaultConversion: '1 Roll = 90 Meters' },
  { id: 'unit-8', code: 'SET', name: 'Sets', uqcCode: 'SET-SETS', description: 'Combined tool set / kit', defaultConversion: 'Base Unit' },
  { id: 'unit-9', code: 'BAG', name: 'Bags', uqcCode: 'BAG-BAGS', description: 'Sacks / compound resin bags', defaultConversion: '1 Bag = 50 KG' },
  { id: 'unit-10', code: 'HRS', name: 'Hours', uqcCode: 'HRS-HOURS', description: 'Service duration billing unit', defaultConversion: 'Base Unit' },
];

export const INITIAL_PARTY_GROUPS: PartyGroup[] = [
  {
    id: 'grp-1',
    name: 'North Region Customers',
    groupType: 'Customer',
    groupBy: 'State',
    locationValue: 'Delhi, Haryana, UP',
    description: 'Direct accounts across Delhi NCR and Northern corridors.',
    color: '#2563eb',
  },
  {
    id: 'grp-2',
    name: 'Western Hub Dealers',
    groupType: 'Customer',
    groupBy: 'State',
    locationValue: 'Maharashtra, Gujarat',
    description: 'Industrial tools wholesalers in Mumbai and Ahmedabad.',
    color: '#7c3aed',
  },
  {
    id: 'grp-3',
    name: 'Key Raw Material Suppliers',
    groupType: 'Supplier',
    groupBy: 'Area',
    locationValue: 'Industrial Belts',
    description: 'Steel, copper, and electrical component principal suppliers.',
    color: '#059669',
  },
  {
    id: 'grp-4',
    name: 'South Zone Distribution',
    groupType: 'All',
    groupBy: 'District',
    locationValue: 'Bengaluru Urban',
    description: 'South electronics components and allied suppliers.',
    color: '#d97706',
  },
];

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Sharma Enterprises Pvt Ltd',
    tradeName: 'Sharma Industrial Supplies',
    phoneNumber: '+91 98765 43210',
    email: 'accounts@sharmaenterprises.in',
    gstin: '07AAAAA0000A1Z5',
    tagline: 'Quality Hardware & Industrial Supplies',
    address: 'Plot 42, Okhla Industrial Area Phase-III, New Delhi - 110020',
    city: 'New Delhi',
    state: 'Delhi (07)',
    businessType: 'Pvt Ltd',
    ownerName: 'Rajesh Sharma',
    currency: 'INR (₹)',
    financialYearStart: '2026-04-01',
    createdAt: '2025-04-01',
    isActive: true,
  },
  {
    id: 'comp-2',
    name: 'Sharma Industrial Logistics & Supply',
    tradeName: 'SIL Logistics',
    phoneNumber: '+91 98110 54321',
    email: 'logistics@sharmagroup.in',
    gstin: '06AAECS9012M1Z8',
    tagline: 'Nationwide Heavy Material Distribution',
    address: 'Shed 18, Udyog Vihar Phase IV, Gurugram - 122015',
    city: 'Gurugram',
    state: 'Haryana (06)',
    businessType: 'Partnership',
    ownerName: 'Amit Sharma',
    currency: 'INR (₹)',
    financialYearStart: '2026-04-01',
    createdAt: '2025-08-15',
    isActive: false,
  },
  {
    id: 'comp-3',
    name: 'BluePeak Tools & Fasteners LLP',
    tradeName: 'BluePeak Hardware',
    phoneNumber: '+91 99234 11223',
    email: 'contact@bluepeaktools.in',
    gstin: '27AABCT4321R1ZT',
    tagline: 'Precision Fasteners & Machinery Components',
    address: 'Shop 12, Lamington Road, Grant Road, Mumbai - 400007',
    city: 'Mumbai',
    state: 'Maharashtra (27)',
    businessType: 'LLP',
    ownerName: 'Sunita Sharma',
    currency: 'INR (₹)',
    financialYearStart: '2026-04-01',
    createdAt: '2026-01-10',
    isActive: false,
  },
];

export const INITIAL_USER: UserAccount = {
  businessName: 'Sharma Enterprises Pvt Ltd',
  phoneNumber: '+91 98765 43210',
  email: 'accounts@sharmaenterprises.in',
  gstin: '07AAAAA0000A1Z5',
  tagline: 'Quality Hardware & Industrial Supplies',
  address: 'Plot 42, Okhla Industrial Area Phase-III, New Delhi - 110020',
  ownerName: 'Rajesh Sharma',
  role: 'Admin',
  isLoggedIn: false, // Initially on registration/login page
};

export const INITIAL_PARTIES: Party[] = [
  {
    id: 'party-1',
    name: 'Apex Infotech Solutions',
    type: 'Customer',
    phone: '+91 98112 34567',
    email: 'billing@apexinfotech.com',
    gstin: '07AAACA1234F1Z8',
    city: 'New Delhi',
    balance: 145200, // Receivable
    creditLimit: 500000,
    paymentTermsDays: 30,
    totalInvoiced: 840000,
    punctualityScore: 94,
  },
  {
    id: 'party-2',
    name: 'Vanguard Industrial Tools Ltd',
    type: 'Customer',
    phone: '+91 99234 56789',
    email: 'accounts@vanguardtools.in',
    gstin: '27AABCV5678K1ZG',
    city: 'Mumbai',
    balance: 89400,
    creditLimit: 300000,
    paymentTermsDays: 15,
    totalInvoiced: 620000,
    punctualityScore: 88,
  },
  {
    id: 'party-3',
    name: 'Bharat Electro Power Hub',
    type: 'Customer',
    phone: '+91 98345 67890',
    email: 'procurement@bharatelectro.com',
    gstin: '06AAEFB9012L1Z3',
    city: 'Gurugram',
    balance: 234500,
    creditLimit: 600000,
    paymentTermsDays: 45,
    totalInvoiced: 1120000,
    punctualityScore: 96,
  },
  {
    id: 'party-4',
    name: 'Royal Hardware & Sanitary Store',
    type: 'Customer',
    phone: '+91 97123 45678',
    email: 'royalhardware.delhi@gmail.com',
    gstin: '07AADCR8765M1Z2',
    city: 'Noida',
    balance: 42000,
    creditLimit: 150000,
    paymentTermsDays: 15,
    totalInvoiced: 380000,
    punctualityScore: 82,
  },
  {
    id: 'party-5',
    name: 'Tata Steel Tubes & Alloys Distributor',
    type: 'Supplier',
    phone: '+91 98450 11223',
    email: 'supply@tatatubesdist.in',
    gstin: '08AABCT4321P1Z9',
    city: 'Jaipur',
    balance: -185000, // Payable
    creditLimit: 1000000,
    paymentTermsDays: 30,
    totalInvoiced: 1450000,
    punctualityScore: 99,
  },
  {
    id: 'party-6',
    name: 'Polycab Electrical Wires Depo',
    type: 'Supplier',
    phone: '+91 98990 88776',
    email: 'dispatch@polycabdepo.in',
    gstin: '24AAACP9988C1ZR',
    city: 'Ahmedabad',
    balance: -92000,
    creditLimit: 800000,
    paymentTermsDays: 30,
    totalInvoiced: 920000,
    punctualityScore: 95,
  },
  {
    id: 'party-7',
    name: 'Schneider Electric Components',
    type: 'Supplier',
    phone: '+91 99100 44556',
    email: 'order@schneiderelec.in',
    gstin: '29AAECS4433D1ZK',
    city: 'Bengaluru',
    balance: -64500,
    creditLimit: 500000,
    paymentTermsDays: 20,
    totalInvoiced: 580000,
    punctualityScore: 92,
  },
];

export const INITIAL_ITEMS: Item[] = [
  // PRODUCTS
  {
    id: 'item-1',
    name: 'Industrial Heavy Duty Drill Machine 850W',
    code: 'DRL-850',
    category: 'Power Tools',
    hsn: '84672100',
    salePrice: 4250,
    purchasePrice: 3200,
    stockQty: 48,
    unit: 'BOX',
    secondaryUnit1: 'PACK',
    secondaryUnit1Rate: 5,
    secondaryUnit2: 'PCS',
    secondaryUnit2Rate: 10,
    itemType: 'Product',
    minStockLevel: 10,
    taxRate: 18,
    unitsSold: 142,
    totalRevenue: 603500,
  },
  {
    id: 'item-2',
    name: 'Polycab Copper Armoured Cable 4-Core 6mm (90m Roll)',
    code: 'CAB-CU4C6',
    category: 'Electricals',
    hsn: '85444990',
    salePrice: 8900,
    purchasePrice: 7200,
    stockQty: 32,
    unit: 'ROLL',
    secondaryUnit1: 'MTR',
    secondaryUnit1Rate: 90,
    itemType: 'Product',
    minStockLevel: 8,
    taxRate: 18,
    unitsSold: 96,
    totalRevenue: 854400,
  },
  {
    id: 'item-3',
    name: 'Schneider 3-Phase MCB 63 Ampere C-Curve',
    code: 'MCB-63A',
    category: 'Switchgear',
    hsn: '85362030',
    salePrice: 1850,
    purchasePrice: 1350,
    stockQty: 0, // 0 Stock (Red badge!)
    unit: 'PCS',
    itemType: 'Product',
    minStockLevel: 15,
    taxRate: 18,
    unitsSold: 215,
    totalRevenue: 397750,
  },
  {
    id: 'item-4',
    name: 'High Tensile Hex Bolt & Nut Set M12x50 (Box of 100)',
    code: 'BLT-M12X50',
    category: 'Fasteners',
    hsn: '73181500',
    salePrice: 780,
    purchasePrice: 540,
    stockQty: -5, // Negative stock (Red badge!)
    unit: 'BOX',
    secondaryUnit1: 'PACK',
    secondaryUnit1Rate: 10,
    secondaryUnit2: 'PCS',
    secondaryUnit2Rate: 10,
    itemType: 'Product',
    minStockLevel: 25,
    taxRate: 18,
    unitsSold: 380,
    totalRevenue: 296400,
  },
  {
    id: 'item-5',
    name: 'Tata Galvanized Iron Pipe 2-inch Class B (6 Meter)',
    code: 'GI-PIPE-2IN',
    category: 'Pipes & Fittings',
    hsn: '73063090',
    salePrice: 3400,
    purchasePrice: 2750,
    stockQty: 64,
    unit: 'MTR',
    itemType: 'Product',
    minStockLevel: 12,
    taxRate: 18,
    unitsSold: 110,
    totalRevenue: 374000,
  },
  {
    id: 'item-6',
    name: 'Bosch Angle Grinder 100mm 720W Professional',
    code: 'GWS-720',
    category: 'Power Tools',
    hsn: '84672900',
    salePrice: 2850,
    purchasePrice: 2150,
    stockQty: 40,
    unit: 'PCS',
    itemType: 'Product',
    minStockLevel: 10,
    taxRate: 18,
    unitsSold: 88,
    totalRevenue: 250800,
  },
  // SERVICES
  {
    id: 'item-srv-1',
    name: 'Industrial Machinery On-Site Fitting & Installation Service',
    code: 'SRV-INST-01',
    category: 'Technical Services',
    hsn: '998719', // SAC code
    salePrice: 3500,
    purchasePrice: 1500,
    stockQty: 10,
    unit: 'HRS',
    itemType: 'Service',
    minStockLevel: 0,
    taxRate: 18,
    unitsSold: 42,
    totalRevenue: 147000,
    description: 'Expert technician deployment for machine assembly and alignment.',
  },
  {
    id: 'item-srv-2',
    name: 'Electrical Panel Annual Maintenance Contract (AMC)',
    code: 'SRV-AMC-ELEC',
    category: 'Maintenance',
    hsn: '998714',
    salePrice: 24000,
    purchasePrice: 12000,
    stockQty: 0, // 0 Available slots (Red badge)
    unit: 'SET',
    itemType: 'Service',
    minStockLevel: 0,
    taxRate: 18,
    unitsSold: 12,
    totalRevenue: 288000,
    description: 'Quarterly audit, preventive thermal imaging & contactor replacement.',
  },
  {
    id: 'item-srv-3',
    name: 'Precision Calibration & ISO Safety Audit',
    code: 'SRV-CALIB-9001',
    category: 'Testing & Quality',
    hsn: '998346',
    salePrice: 8500,
    purchasePrice: 4000,
    stockQty: 15,
    unit: 'PCS',
    itemType: 'Service',
    minStockLevel: 0,
    taxRate: 18,
    unitsSold: 28,
    totalRevenue: 238000,
  },
  // RAW MATERIALS
  {
    id: 'item-raw-1',
    name: 'High Grade Copper Rod Scrap (Industrial Grade A)',
    code: 'RAW-CU-ROD',
    category: 'Raw Metals',
    hsn: '74040012',
    salePrice: 760,
    purchasePrice: 680,
    stockQty: 450,
    unit: 'KG',
    secondaryUnit1: 'GM',
    secondaryUnit1Rate: 1000,
    itemType: 'Raw Material',
    minStockLevel: 100,
    taxRate: 18,
    unitsSold: 1250,
    totalRevenue: 950000,
  },
  {
    id: 'item-raw-2',
    name: 'Industrial Polymer Resin Granules HD-90',
    code: 'RAW-POLY-HD90',
    category: 'Plastics & Polymers',
    hsn: '39012000',
    salePrice: 180,
    purchasePrice: 145,
    stockQty: 0, // Out of stock raw material (Red badge)
    unit: 'BAG',
    secondaryUnit1: 'KG',
    secondaryUnit1Rate: 50,
    itemType: 'Raw Material',
    minStockLevel: 50,
    taxRate: 18,
    unitsSold: 800,
    totalRevenue: 144000,
  },
  {
    id: 'item-raw-3',
    name: 'Stainless Steel Cold Rolled Sheet 304 Grade 2mm',
    code: 'RAW-SS304-2MM',
    category: 'Raw Metals',
    hsn: '72193390',
    salePrice: 320,
    purchasePrice: 260,
    stockQty: 120,
    unit: 'KG',
    itemType: 'Raw Material',
    minStockLevel: 30,
    taxRate: 18,
    unitsSold: 640,
    totalRevenue: 204800,
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-0089',
    type: 'Sale',
    partyId: 'party-1',
    partyName: 'Apex Infotech Solutions',
    partyPhone: '+91 98112 34567',
    partyGstin: '07AAACA1234F1Z8',
    date: '2026-08-22',
    dueDate: '2026-09-06',
    fiscalYear: 'FY 2026-27',
    items: [
      { itemId: 'item-2', itemName: 'Polycab Copper Armoured Cable 4-Core 6mm', hsn: '85444990', qty: 10, unit: 'ROLL', rate: 8900, taxRate: 18, discountPct: 5, amount: 84550 },
      { itemId: 'item-3', itemName: 'Schneider 3-Phase MCB 63 Ampere C-Curve', hsn: '85362030', qty: 20, unit: 'PCS', rate: 1850, taxRate: 18, discountPct: 0, amount: 37000 },
    ],
    subtotal: 121550,
    taxTotal: 21879,
    discountTotal: 4450,
    roundOff: 0.0,
    grandTotal: 143429,
    receivedPaidAmount: 0,
    balanceDue: 143429,
    paymentMode: 'Bank Transfer / NEFT',
    status: 'Unpaid',
    notes: 'Site installation batch 4. Dispatch via BlueDart.',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-0088',
    type: 'Sale',
    partyId: 'party-3',
    partyName: 'Bharat Electro Power Hub',
    partyPhone: '+91 98345 67890',
    partyGstin: '06AAEFB9012L1Z3',
    date: '2026-08-18',
    dueDate: '2026-09-15',
    fiscalYear: 'FY 2026-27',
    items: [
      { itemId: 'item-1', itemName: 'Industrial Heavy Duty Drill Machine 850W', hsn: '84672100', qty: 15, unit: 'PCS', rate: 4250, taxRate: 18, discountPct: 2, amount: 62475 },
      { itemId: 'item-5', itemName: 'Tata Galvanized Iron Pipe 2-inch Class B', hsn: '73063090', qty: 25, unit: 'LENGTH', rate: 3400, taxRate: 18, discountPct: 0, amount: 85000 },
    ],
    subtotal: 147475,
    taxTotal: 26545.5,
    discountTotal: 1275,
    roundOff: 0.5,
    grandTotal: 174021,
    receivedPaidAmount: 174021,
    balanceDue: 0,
    paymentMode: 'UPI',
    status: 'Paid',
    notes: 'Payment confirmed via ICICI UPI QR.',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-0085',
    type: 'Sale',
    partyId: 'party-2',
    partyName: 'Vanguard Industrial Tools Ltd',
    partyPhone: '+91 99234 56789',
    partyGstin: '27AABCV5678K1ZG',
    date: '2026-08-10',
    dueDate: '2026-08-25',
    fiscalYear: 'FY 2026-27',
    items: [
      { itemId: 'item-6', itemName: 'Bosch Angle Grinder 100mm 720W', hsn: '84672900', qty: 12, unit: 'PCS', rate: 2850, taxRate: 18, discountPct: 0, amount: 34200 },
      { itemId: 'item-4', itemName: 'High Tensile Hex Bolt & Nut Set M12x50', hsn: '73181500', qty: 30, unit: 'BOX', rate: 780, taxRate: 18, discountPct: 5, amount: 22230 },
    ],
    subtotal: 56430,
    taxTotal: 10157.4,
    discountTotal: 1170,
    roundOff: 0.6,
    grandTotal: 66588,
    receivedPaidAmount: 30000,
    balanceDue: 36588,
    paymentMode: 'Cheque',
    status: 'Partially Paid',
    notes: 'Cheque no 44091 cleared for advance.',
  },
  {
    id: 'inv-104',
    invoiceNumber: 'INV-2026-0072',
    type: 'Sale',
    partyId: 'party-4',
    partyName: 'Royal Hardware & Sanitary Store',
    partyPhone: '+91 97123 45678',
    partyGstin: '07AADCR8765M1Z2',
    date: '2026-07-28',
    dueDate: '2026-08-12',
    fiscalYear: 'FY 2026-27',
    items: [
      { itemId: 'item-7', itemName: 'Brass Ball Valve 1-inch Full Bore', hsn: '84818030', qty: 50, unit: 'PCS', rate: 620, taxRate: 18, discountPct: 0, amount: 31000 },
    ],
    subtotal: 31000,
    taxTotal: 5580,
    discountTotal: 0,
    roundOff: 0.0,
    grandTotal: 36580,
    receivedPaidAmount: 0,
    balanceDue: 36580,
    paymentMode: 'Credit',
    status: 'Overdue',
    notes: 'Followed up on 18th August. Promoted for settlement.',
  },
  {
    id: 'pur-201',
    invoiceNumber: 'PUR-2026-0045',
    type: 'Purchase',
    partyId: 'party-5',
    partyName: 'Tata Steel Tubes & Alloys Distributor',
    partyPhone: '+91 98450 11223',
    partyGstin: '08AABCT4321P1Z9',
    date: '2026-08-15',
    dueDate: '2026-09-14',
    fiscalYear: 'FY 2026-27',
    items: [
      { itemId: 'item-5', itemName: 'Tata Galvanized Iron Pipe 2-inch Class B', hsn: '73063090', qty: 50, unit: 'LENGTH', rate: 2750, taxRate: 18, discountPct: 0, amount: 137500 },
    ],
    subtotal: 137500,
    taxTotal: 24750,
    discountTotal: 0,
    roundOff: 0.0,
    grandTotal: 162250,
    receivedPaidAmount: 100000,
    balanceDue: 62250,
    paymentMode: 'Bank Transfer / NEFT',
    status: 'Partially Paid',
  },
  {
    id: 'pur-202',
    invoiceNumber: 'PUR-2026-0044',
    type: 'Purchase',
    partyId: 'party-6',
    partyName: 'Polycab Electrical Wires Depo',
    partyPhone: '+91 98990 88776',
    partyGstin: '24AAACP9988C1ZR',
    date: '2026-08-05',
    dueDate: '2026-09-04',
    fiscalYear: 'FY 2026-27',
    items: [
      { itemId: 'item-2', itemName: 'Polycab Copper Armoured Cable 4-Core 6mm', hsn: '85444990', qty: 25, unit: 'ROLL', rate: 7200, taxRate: 18, discountPct: 0, amount: 180000 },
    ],
    subtotal: 180000,
    taxTotal: 32400,
    discountTotal: 0,
    roundOff: 0.0,
    grandTotal: 212400,
    receivedPaidAmount: 212400,
    balanceDue: 0,
    paymentMode: 'Bank Transfer / NEFT',
    status: 'Paid',
  },
  // FY 2025-26 records for multi-year filter verification
  {
    id: 'inv-prev-1',
    invoiceNumber: 'INV-2025-0450',
    type: 'Sale',
    partyId: 'party-1',
    partyName: 'Apex Infotech Solutions',
    partyPhone: '+91 98112 34567',
    partyGstin: '07AAACA1234F1Z8',
    date: '2025-11-14',
    dueDate: '2025-11-29',
    fiscalYear: 'FY 2025-26',
    items: [
      { itemId: 'item-1', itemName: 'Industrial Heavy Duty Drill Machine 850W', hsn: '84672100', qty: 30, unit: 'PCS', rate: 4100, taxRate: 18, discountPct: 0, amount: 123000 },
    ],
    subtotal: 123000,
    taxTotal: 22140,
    discountTotal: 0,
    roundOff: 0.0,
    grandTotal: 145140,
    receivedPaidAmount: 145140,
    balanceDue: 0,
    paymentMode: 'Bank Transfer / NEFT',
    status: 'Paid',
  },
  {
    id: 'inv-prev-2',
    invoiceNumber: 'INV-2025-0512',
    type: 'Sale',
    partyId: 'party-3',
    partyName: 'Bharat Electro Power Hub',
    partyPhone: '+91 98345 67890',
    partyGstin: '06AAEFB9012L1Z3',
    date: '2026-02-10',
    dueDate: '2026-02-25',
    fiscalYear: 'FY 2025-26',
    items: [
      { itemId: 'item-2', itemName: 'Polycab Copper Armoured Cable 4-Core 6mm', hsn: '85444990', qty: 20, unit: 'ROLL', rate: 8700, taxRate: 18, discountPct: 0, amount: 174000 },
    ],
    subtotal: 174000,
    taxTotal: 31320,
    discountTotal: 0,
    roundOff: 0.0,
    grandTotal: 205320,
    receivedPaidAmount: 205320,
    balanceDue: 0,
    paymentMode: 'UPI',
    status: 'Paid',
  },
  {
    id: 'pur-prev-1',
    invoiceNumber: 'PUR-2025-0210',
    type: 'Purchase',
    partyId: 'party-5',
    partyName: 'Tata Steel Tubes & Alloys Distributor',
    partyPhone: '+91 98450 11223',
    date: '2025-10-18',
    dueDate: '2025-11-17',
    fiscalYear: 'FY 2025-26',
    items: [
      { itemId: 'item-5', itemName: 'Tata Galvanized Iron Pipe 2-inch Class B', hsn: '73063090', qty: 60, unit: 'LENGTH', rate: 2650, taxRate: 18, discountPct: 0, amount: 159000 },
    ],
    subtotal: 159000,
    taxTotal: 28620,
    discountTotal: 0,
    roundOff: 0.0,
    grandTotal: 187620,
    receivedPaidAmount: 187620,
    balanceDue: 0,
    paymentMode: 'Bank Transfer / NEFT',
    status: 'Paid',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    expenseNumber: 'EXP-2026-012',
    date: '2026-08-01',
    fiscalYear: 'FY 2026-27',
    category: 'Rent',
    payee: 'Okhla Industrial Estates Landlord Association',
    amount: 65000,
    taxRate: 18,
    paymentMode: 'Bank',
    status: 'Paid',
    taxDeductible: true,
    notes: 'August 2026 Warehouse lease rental',
  },
  {
    id: 'exp-2',
    expenseNumber: 'EXP-2026-013',
    date: '2026-08-05',
    fiscalYear: 'FY 2026-27',
    category: 'Electricity & Utility',
    payee: 'BSES Rajdhani Power Limited',
    amount: 18450,
    taxRate: 18,
    paymentMode: 'UPI',
    status: 'Paid',
    taxDeductible: true,
    notes: 'Commercial 3-phase meter bill #392810',
  },
  {
    id: 'exp-3',
    expenseNumber: 'EXP-2026-014',
    date: '2026-08-07',
    fiscalYear: 'FY 2026-27',
    category: 'Staff Salary',
    payee: 'Store & Logistics Crew (5 Members)',
    amount: 110000,
    taxRate: 0,
    paymentMode: 'Bank',
    status: 'Paid',
    taxDeductible: true,
    notes: 'Monthly payroll disbursement',
  },
  {
    id: 'exp-4',
    expenseNumber: 'EXP-2026-015',
    date: '2026-08-12',
    fiscalYear: 'FY 2026-27',
    category: 'Freight & Logistics',
    payee: 'Delhi-NCR Express Logistics Transport',
    amount: 14200,
    taxRate: 5,
    paymentMode: 'Cash',
    status: 'Paid',
    taxDeductible: true,
    notes: 'Interstate dispatches and octroi charges',
  },
  {
    id: 'exp-prev-1',
    expenseNumber: 'EXP-2025-088',
    date: '2025-12-05',
    fiscalYear: 'FY 2025-26',
    category: 'Office Supplies',
    payee: 'Modern Stationery & Printing Hub',
    amount: 9800,
    taxRate: 18,
    paymentMode: 'UPI',
    status: 'Paid',
    taxDeductible: true,
  },
];

export const INITIAL_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'bank-1',
    accountName: 'HDFC Current Primary',
    bankName: 'HDFC Bank Ltd',
    accountNumber: '50200049281734',
    ifsc: 'HDFC0000128',
    accountType: 'Current',
    currentBalance: 842500,
    upiId: 'sharmaent@hdfcbank',
    isPrimary: true,
  },
  {
    id: 'bank-2',
    accountName: 'ICICI Business OD Account',
    bankName: 'ICICI Bank',
    accountNumber: '003205018920',
    ifsc: 'ICIC0000032',
    accountType: 'Overdraft',
    currentBalance: 320000,
    upiId: 'sharmaenterprises@icici',
    isPrimary: false,
  },
  {
    id: 'bank-3',
    accountName: 'Main Cash Drawer',
    bankName: 'Cash In Hand',
    accountNumber: 'CASH-MAIN-DRAWER',
    ifsc: 'NA',
    accountType: 'Cash In Hand',
    currentBalance: 48900,
    isPrimary: false,
  },
];

export const INITIAL_TAX_CONFIG: TaxConfiguration = {
  defaultGstRate: 18,
  enabledSlabs: [0, 5, 12, 18, 28],
  enableCess: false,
  enableCompositionScheme: false,
  enableAutoRoundOff: true,
  enableEInvoice: true,
  enableEWayBill: true,
  reverseChargeApplicable: false,
  invoicePrefix: 'INV-2026-',
  financialYearStart: 'April 1',
};
