import { ThemeConfig, ThemeKey } from './types';

export const THEMES: Record<ThemeKey, ThemeConfig> = {
  royal_blue: {
    id: 'royal_blue',
    name: 'Royal Blue & White',
    subtitle: 'Classic corporate & dependable billing aesthetic',
    primaryColor: '#1e40af',
    secondaryColor: '#2563eb',
    sidebarBg: 'bg-gradient-to-b from-[#0f172a] via-[#1e293b] to-[#0f172a] text-slate-100',
    sidebarText: 'text-slate-200',
    accentBg: 'bg-blue-600',
    accentText: 'text-blue-600',
    cardBorder: 'border-blue-100',
    buttonClass: 'bg-blue-700 hover:bg-blue-800 text-white shadow-blue-900/20',
    activeNavClass: 'bg-blue-600 text-white shadow-md shadow-blue-900/40',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    appBg: '#f8fafc',
    cardBorderHex: '#dbeafe',
    badgeBgHex: '#eff6ff',
    badgeTextHex: '#1e40af',
    tableHeaderBg: '#f1f5f9',
    headerBg: '#ffffff',
    activeTabClass: 'bg-blue-600 text-white',
    chartColors: {
      primary: '#2563eb',
      secondary: '#0ea5e9',
      tertiary: '#93c5fd',
      accent: '#3b82f6',
    },
  },
  teal_gray: {
    id: 'teal_gray',
    name: 'Teal & Gray',
    subtitle: 'Calm modern fintech balance with cool slate neutrals',
    primaryColor: '#0f766e',
    secondaryColor: '#0d9488',
    sidebarBg: 'bg-gradient-to-b from-[#132a2a] via-[#1a3838] to-[#112424] text-slate-100',
    sidebarText: 'text-teal-100',
    accentBg: 'bg-teal-600',
    accentText: 'text-teal-700',
    cardBorder: 'border-teal-100',
    buttonClass: 'bg-teal-700 hover:bg-teal-800 text-white shadow-teal-900/20',
    activeNavClass: 'bg-teal-600 text-white shadow-md shadow-teal-950/40',
    badgeClass: 'bg-teal-50 text-teal-800 border-teal-200',
    appBg: '#f0fdfa',
    cardBorderHex: '#ccfbf1',
    badgeBgHex: '#e6fffa',
    badgeTextHex: '#0f766e',
    tableHeaderBg: '#f0fdfa',
    headerBg: '#ffffff',
    activeTabClass: 'bg-teal-600 text-white',
    chartColors: {
      primary: '#0d9488',
      secondary: '#2dd4bf',
      tertiary: '#99f6e4',
      accent: '#14b8a6',
    },
  },
  purple_lavender: {
    id: 'purple_lavender',
    name: 'Purple & Lavender',
    subtitle: 'Sophisticated luxury palette with soft pastel contrasts',
    primaryColor: '#6d28d9',
    secondaryColor: '#7c3aed',
    sidebarBg: 'bg-gradient-to-b from-[#1e1435] via-[#2c1b4d] to-[#190f2d] text-slate-100',
    sidebarText: 'text-purple-100',
    accentBg: 'bg-purple-600',
    accentText: 'text-purple-700',
    cardBorder: 'border-purple-100',
    buttonClass: 'bg-purple-700 hover:bg-purple-800 text-white shadow-purple-900/20',
    activeNavClass: 'bg-purple-600 text-white shadow-md shadow-purple-950/40',
    badgeClass: 'bg-purple-50 text-purple-800 border-purple-200',
    appBg: '#faf5ff',
    cardBorderHex: '#f3e8ff',
    badgeBgHex: '#f3e8ff',
    badgeTextHex: '#6d28d9',
    tableHeaderBg: '#faf5ff',
    headerBg: '#ffffff',
    activeTabClass: 'bg-purple-600 text-white',
    chartColors: {
      primary: '#7c3aed',
      secondary: '#c084fc',
      tertiary: '#e9d5ff',
      accent: '#9333ea',
    },
  },
  emerald_mint: {
    id: 'emerald_mint',
    name: 'Emerald Green & Mint',
    subtitle: 'Prosperity & growth theme inspired by banking ledgers',
    primaryColor: '#047857',
    secondaryColor: '#059669',
    sidebarBg: 'bg-gradient-to-b from-[#0c241b] via-[#13382b] to-[#0a1e16] text-slate-100',
    sidebarText: 'text-emerald-100',
    accentBg: 'bg-emerald-600',
    accentText: 'text-emerald-700',
    cardBorder: 'border-emerald-100',
    buttonClass: 'bg-emerald-700 hover:bg-emerald-800 text-white shadow-emerald-900/20',
    activeNavClass: 'bg-emerald-600 text-white shadow-md shadow-emerald-950/40',
    badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    appBg: '#f0fdf4',
    cardBorderHex: '#dcfce7',
    badgeBgHex: '#dcfce7',
    badgeTextHex: '#047857',
    tableHeaderBg: '#f0fdf4',
    headerBg: '#ffffff',
    activeTabClass: 'bg-emerald-600 text-white',
    chartColors: {
      primary: '#059669',
      secondary: '#34d399',
      tertiary: '#a7f3d0',
      accent: '#10b981',
    },
  },
  amber_orange: {
    id: 'amber_orange',
    name: 'Amber & Orange',
    subtitle: 'High-energy commerce theme for fast-paced trading',
    primaryColor: '#b45309',
    secondaryColor: '#d97706',
    sidebarBg: 'bg-gradient-to-b from-[#291b0f] via-[#3d2714] to-[#21150c] text-slate-100',
    sidebarText: 'text-amber-100',
    accentBg: 'bg-amber-600',
    accentText: 'text-amber-700',
    cardBorder: 'border-amber-100',
    buttonClass: 'bg-amber-600 hover:bg-amber-700 text-white shadow-amber-900/20',
    activeNavClass: 'bg-amber-600 text-white shadow-md shadow-amber-950/40',
    badgeClass: 'bg-amber-50 text-amber-900 border-amber-200',
    appBg: '#fffbeb',
    cardBorderHex: '#fef3c7',
    badgeBgHex: '#fef3c7',
    badgeTextHex: '#b45309',
    tableHeaderBg: '#fffbeb',
    headerBg: '#ffffff',
    activeTabClass: 'bg-amber-600 text-white',
    chartColors: {
      primary: '#d97706',
      secondary: '#fb923c',
      tertiary: '#fed7aa',
      accent: '#f59e0b',
    },
  },
  coral_peach: {
    id: 'coral_peach',
    name: 'Coral & Peach',
    subtitle: 'Warm contemporary retail & boutique billing atmosphere',
    primaryColor: '#be123c',
    secondaryColor: '#e11d48',
    sidebarBg: 'bg-gradient-to-b from-[#2b1019] via-[#3d1623] to-[#200c13] text-slate-100',
    sidebarText: 'text-rose-100',
    accentBg: 'bg-rose-600',
    accentText: 'text-rose-700',
    cardBorder: 'border-rose-100',
    buttonClass: 'bg-rose-600 hover:bg-rose-700 text-white shadow-rose-900/20',
    activeNavClass: 'bg-rose-600 text-white shadow-md shadow-rose-950/40',
    badgeClass: 'bg-rose-50 text-rose-900 border-rose-200',
    appBg: '#fff1f2',
    cardBorderHex: '#ffe4e6',
    badgeBgHex: '#ffe4e6',
    badgeTextHex: '#be123c',
    tableHeaderBg: '#fff1f2',
    headerBg: '#ffffff',
    activeTabClass: 'bg-rose-600 text-white',
    chartColors: {
      primary: '#e11d48',
      secondary: '#fb7185',
      tertiary: '#fecdd3',
      accent: '#f43f5e',
    },
  },
  slate_gray: {
    id: 'slate_gray',
    name: 'Slate Blue & Gray',
    subtitle: 'Minimalist industrial desktop accounting interface',
    primaryColor: '#334155',
    secondaryColor: '#475569',
    sidebarBg: 'bg-gradient-to-b from-[#0f172a] via-[#1e293b] to-[#0b1120] text-slate-100',
    sidebarText: 'text-slate-200',
    accentBg: 'bg-slate-700',
    accentText: 'text-slate-800',
    cardBorder: 'border-slate-200',
    buttonClass: 'bg-slate-800 hover:bg-slate-900 text-white shadow-slate-900/20',
    activeNavClass: 'bg-slate-700 text-white shadow-md shadow-slate-950/40',
    badgeClass: 'bg-slate-100 text-slate-800 border-slate-300',
    appBg: '#f8fafc',
    cardBorderHex: '#e2e8f0',
    badgeBgHex: '#f1f5f9',
    badgeTextHex: '#334155',
    tableHeaderBg: '#f8fafc',
    headerBg: '#ffffff',
    activeTabClass: 'bg-slate-700 text-white',
    chartColors: {
      primary: '#475569',
      secondary: '#94a3b8',
      tertiary: '#cbd5e1',
      accent: '#64748b',
    },
  },
  indigo_sky: {
    id: 'indigo_sky',
    name: 'Indigo & Sky Blue',
    subtitle: 'Vibrant tech-enabled enterprise workflow combination',
    primaryColor: '#4338ca',
    secondaryColor: '#4f46e5',
    sidebarBg: 'bg-gradient-to-b from-[#141838] via-[#1c224e] to-[#0f122c] text-slate-100',
    sidebarText: 'text-indigo-100',
    accentBg: 'bg-indigo-600',
    accentText: 'text-indigo-700',
    cardBorder: 'border-indigo-100',
    buttonClass: 'bg-indigo-700 hover:bg-indigo-800 text-white shadow-indigo-900/20',
    activeNavClass: 'bg-indigo-600 text-white shadow-md shadow-indigo-950/40',
    badgeClass: 'bg-indigo-50 text-indigo-800 border-indigo-200',
    appBg: '#f5f3ff',
    cardBorderHex: '#e0e7ff',
    badgeBgHex: '#e0e7ff',
    badgeTextHex: '#4338ca',
    tableHeaderBg: '#f5f3ff',
    headerBg: '#ffffff',
    activeTabClass: 'bg-indigo-600 text-white',
    chartColors: {
      primary: '#4f46e5',
      secondary: '#0284c7',
      tertiary: '#bae6fd',
      accent: '#38bdf8',
    },
  },
};
